### ISSUE TITLE
Forward declared template functions not correctly pruned

### ISSUE THREAD

**Issue by psalz** [illuhad/hipSYCL#14]
Consider this simple program:

```c++
template<typename T>
void foo(T);

template <typename T>
void bar(T) {}

template<typename T>
void foo(T value) {
    bar(value);
}

int main() {
    return 0;
}                                                              
```

After the rewrite and transformation passes, `nvcc` complains with `#endif without #if` and `unterminated #if`. The temporary *.cu file reveals the reason:

```c++
# 1 "<built-in>"
# 1 "/tmp/forward_decl.cpp"
template<typename T>
void foo(T)
#endif
;

template <typename T>
void bar(T) {}

template<typename T>
void foo(T value) ;
#if 0 // -- definition stripped by hipsycl_transform_source
{
        bar(value);
}

int main() {
        return 0;
}
```

Apparently, according to the Clang AST, the beginning of the body is at the definition, while the end is at the declaration. This of course causes a complete mess and breaks compilation of larger headers (e.g. Boost). I've been told that his might be annoying to fix, so my question is: Why are you pruning these uninstantiated templates anyway? Is this just an optimization or is there a practical reason?

**Comment by illuhad** [comment]
The reason for pruning uninstantiated templates is that clang and nvcc have subtle differences with regards to overload resolution in uninstantiated templates. In order to correct `__host__` and `__device__` attributes perfectly, we need to have an accurate call graph that, in particular, matches the call graph that nvcc works with. 
As it turns out, there are cases where clang cannot resolve called overloaded functions within uninstantiated templates while nvcc still resolves them. Consequently, we may have missing edges in the clang call graph, and hence also miss information to infer whether a function should be host or device. Since nvcc still sees these edges, it may complain about missing `__device__` or `__host__` attributes. At the time, I thought that just removing such functions entirely from the code would be the most robust solution to this problem. This was also the final ingredient that allowed me to compile SYCL parallel STL code. 

There surely must be a way to get the actual beginning and end of the code block in the AST? Otherwise we could also try removing only the problematic function calls, but I'm not sure if this would be simpler in general, especially since function calls can be parts of other statements or calls.

**Comment by psalz** [comment]
I see. Well, I talked to some compiler guys in my office and was told that they encountered this issue some years ago and back then it was a pain to work around. Of course that might be different today! I'm not really familiar with LLVM/Clang, but I know someone who is! Ping @PeterTh

**Comment by illuhad** [comment]
@psalz Could you please check if PR #15 fixes this issue for you? I replaced `getBeginLoc()` and `getEndLoc()` with `getSourceRange().getBegin()` and `getSourceRange().getEnd()`, which seem to return the expected locations. With this change, your input case was handled correctly for me.
