### ISSUE TITLE
build issues using ubuntu 0.8.0 binary release

### ISSUE THREAD

**Issue by cgleggett** [illuhad/hipSYCL#145]
installed the 0.8.0 binaries on ubuntu 18.04.

system has an AMD Radeon RX 550X

when linking:
```
> /opt/hipSYCL/bin/syclcc-clang -std=c++11 --hipsycl-platform=rocm -o FP.o -c FP.cpp
syclcc fatal error: Required command line argument --hipsycl-gpu-arch or environment variable HIPSYCL_GPU_ARCH not specified
```

not sure what to set `hipsycl-gpu-arch` to. Better info in docs definitely needed here!

let's pretend it's an nvidia:
```
> /opt/hipSYCL/bin/syclcc-clang -std=c++11 --hipsycl-platform=rocm --hipsycl-gpu-arch=sm_61 -o FP.o -c FP.cpp
clang-9: error: no such file or directory: 'oclc_isa_version_61.amdgcn.bc'
```

ok, so let's look for files that match `oclc_isa_version_XXX.amdgcn.bc`. `clinfo` reports a **gfx803** device, so let's try that:
```
> ls /opt/rocm/lib/oclc_isa_version_803.amdgcn.bc
4 /opt/rocm/lib/oclc_isa_version_803.amdgcn.bc

> /opt/hipSYCL/bin/syclcc-clang --hipsycl-platform=rocm --hipsycl-gpu-arch=803 -o FP.o -c FP.cpp
clang-9: error: Unsupported CUDA gpu architecture: 803
```
why is it complaining about CUDA this time?

let's try the device name explicitly

```
/opt/hipSYCL/bin/syclcc-clang -std=c++14 --hipsycl-platform=rocm --hipsycl-gpu-arch=gfx803 -o FP.o -c FP.cpp 
In file included from FP.cpp:8:
./work.h:13:25: error: no member named 'cl_short' in namespace 'cl::sycl'
  std::vector<cl::sycl::cl_short> VRI;
              ~~~~~~~~~~^
FP.cpp:21:42: error: no member named 'cl_short' in namespace 'cl::sycl'
float find_prime_i(std::vector<cl::sycl::cl_short>& VRI, size_t N, size_t niter, work* w, cl::sycl::queue *dq) {
                               ~~~~~~~~~~^
FP.cpp:21:42: error: no member named 'cl_short' in namespace 'cl::sycl'
float find_prime_i(std::vector<cl::sycl::cl_short>& VRI, size_t N, size_t niter, work* w, cl::sycl::queue *dq) {
                               ~~~~~~~~~~^
FP.cpp:24:30: error: no member named 'cl_short' in namespace 'cl::sycl'
  cl::sycl::buffer<cl::sycl::cl_short, 1> bufferR(VRI.data(), numOfItems);
                   ~~~~~~~~~~^
FP.cpp:24:43: error: C++ requires a type specifier for all declarations
  cl::sycl::buffer<cl::sycl::cl_short, 1> bufferR(VRI.data(), numOfItems);
```

work.h looks like:
<details>

```
#ifndef WORK_H
#define WORK_H 1
#include <mutex>
#include <chrono>
#include <CL/sycl.hpp>

struct work {
  int id;
  size_t size;
  size_t niter;

  std::vector<cl::sycl::cl_short> VRI;
  
  size_t result;
  bool success { false };
  std::chrono::high_resolution_clock::time_point start;
  float elapsed {0.}, wait {0.}, run {0.};
  unsigned long submit_time{0}, start_time{0}, end_time{0};
  std::mutex* queueLock {nullptr};
};  
#endif
```
</details>

what am I missing?

this program compiles cleanly with intel and codeplay versions of sycl.

**Comment by illuhad** [comment]
You are facing two separate issues:
1.) GPU arch is the ROCm GPU arch, so gfx803 in your case. However, Polaris 11/12 GPUs like RX550 are not officially supported by ROCm anymore, so you'll likely face runtime issues. You'll have to complain to AMD about them not supporting their hardware on their own compute stack, nothing I can do.
In general, since hipSYCL builds on ROCm, it is worth reading AMD's ROCm documentation since everything there also applies directly to hipSYCL.
2.) hipSYCL does not rely on OpenCL (as such, any form of OpenCL interoperability is unsupported in general). We do not define these OpenCL types by default since this would cause multiple definition errors when an application also includes OpenCL headers (like SYCL conformance test suite does).
You can tell hipSYCL to try to emulate these types by compiling with `-DHIPSYCL_DEFINE_OPENCL_TYPES`.

**Comment by illuhad** [comment]
I forgot: It's not hipSYCL that is complaining about CUDA, it's clang. clang's HIP and CUDA frontends share so much code that HIP compilation may talk about CUDA. This is something that would need to be addressed by AMD in upstream clang.

**Comment by cgleggett** [comment]
thanks. It does not like any form of cl_short. replaced it with just a `short`, and that worked.

I see that `cl::sycl::stream` is not supported, which makes debugging more challenging. As is the templated `cl::sycl::get_profiling_info< EVENT_TYPE >`.

When I did get things to compile I get a runtime error of:
```
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -48 (CL_INVALID_KERNEL) -48 (CL_INVALID_KERNEL)
```

is this due to what you stated about AMD not supporting rocm on the RX550, or something else?

What AMD GPU card _would_ work? Would a Vega 56?

**Comment by illuhad** [comment]
> I see that cl::sycl::stream is not supported, which makes debugging more challenging. As is the templated cl::sycl::get_profiling_info< EVENT_TYPE >.

you can try `printf()` instead - it works reliably on CUDA but may be a bit fiddly on ROCm (also affects regular HIP, independently of hipSYCL). Alternatively you can also just compile for CPU and debug on host.

> is this due to what you stated about AMD not supporting rocm on the RX550, or something else?

Are you are using any form OpenCL interoperability? If not then this is most likely because of RX550. I haven't seen such an error before on supported GPUs.

As a rule of thumb, AMD focuses their support on GPUs that also have a Radeon Instinct data center variant, i.e. Fiji, Vega, Vega 20 chips. So, a Vega 56 should work.
