### ISSUE TITLE
compile problem on Centos7 w/ release 0.8.0

### ISSUE THREAD

**Issue by cgleggett** [illuhad/hipSYCL#147]
After installing the binary distribution of release 0.8.0 for centos7, I'm seeing some unusual errors when compiling, and lots and lots of errors during the final linking phase:

```
> scl enable rh-python36 devtoolset-7 /bin/bash
> /opt/hipSYCL/bin/syclcc-clang -std=c++14 --hipsycl-platform=rocm --hipsycl-gpu-arch=gfx900 -g -pthread -o FindPrimesSYCL.o -c FindPrimesSYCL.cpp
In file included from FindPrimesSYCL.cpp:1:
In file included from /opt/hipSYCL/bin/../include/CL/sycl.hpp:36:
In file included from /opt/hipSYCL/bin/../include/CL/sycl/backend/backend.hpp:55:
In file included from /opt/hipSYCL/rocm/include/hip/hip_runtime.h:56:
In file included from /opt/hipSYCL/rocm/include/hip/hcc_detail/hip_runtime.h:105:
> /opt/hipSYCL/rocm/include/hip/hcc_detail/texture_functions.h:173:5: warning: array designators are a C99 extension [-Wc99-designator]
    [HIP_AD_FORMAT_NOT_INITIALIZED] = 1  ,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated when compiling for gfx900.
In file included from FindPrimesSYCL.cpp:1:
In file included from /opt/hipSYCL/bin/../include/CL/sycl.hpp:36:
In file included from /opt/hipSYCL/bin/../include/CL/sycl/backend/backend.hpp:55:
In file included from /opt/hipSYCL/rocm/include/hip/hip_runtime.h:56:
In file included from /opt/hipSYCL/rocm/include/hip/hcc_detail/hip_runtime.h:105:
> /opt/hipSYCL/rocm/include/hip/hcc_detail/texture_functions.h:173:5: warning: array designators are a C99 extension [-Wc99-designator]
    [HIP_AD_FORMAT_NOT_INITIALIZED] = 1  ,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated when compiling for host.
> /opt/hipSYCL/bin/syclcc-clang -std=c++14 --hipsycl-platform=rocm --hipsycl-gpu-arch=gfx900 -g -pthread -o Crunch.o -c Crunch.cpp


/opt/hipSYCL/bin/syclcc-clang -std=c++14 --hipsycl-platform=rocm --hipsycl-gpu-arch=gfx900 -g -pthread Crunch.o FindPrimesSYCL.o main.cpp -o fp 
Crunch.o:1:1: error: expected unqualified-id
<U+007F>ELF<U+0002><U+0001><U+0001><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0001><U+0000>><U+0000><U+0001><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0008>[<U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>@<U+0000><U+0000><U+0000><U+0000><U+0000>@<U+0000>-<U+0000><U+0001><U+0000>UH<89><E5>H<81><EC><90><U+0000><U+0000><U+0000>1<C0>H<89>}<F8><89>u<F4>H<8D>M<E8>H<89>ωƺ<U+0008><U+0000><U+0000><U+0000><E8><U+0000><U+0000><U+0000><U+0000><E8><U+0000><U+0000><U+0000><U+0000>H<89>E<E0><C7>E<D8><U+0001><U+0000><U+0000><U+0000><8B>u<U+0609><F0><B9><U+0008><U+0000><U+0000><U+0000>H<F7><E1>A<U+000F><90><C0>H<C7><C1><FF><FF><FF><FF>H<U+000F>@<C1>H<89><C7>D<88>E<87><E8><U+0000><U+0000><U+0000><U+0000>H<89>E<D0>H<8B>E<D0>H<C7><U+0000><U+0002><U+0000><U+0000><U+0000>H<C7>E<C8><U+0002><U+0000><U+0000><U+0000>H<C7>E<C0><U+0000><U+0000><U+0000><U+0000>H<8B>E<C0><8B>M<F4><89><CA>H9<D0><U+000F><83>H<U+0001><U+0000><U+0000>H<8B>E<C8>H<U+0005><U+0001><U+0000><U+0000><U+0000>H<89>E<C8><C6>E<DF><U+0001>H<C7>E<B8><U+0002><U+0000><U+0000><U+0000>1<C0>H<8B>M<B8>H;MȈE<86><U+000F><83><U+0006><U+0000><U+0000><U+0000><8A>E߈E<86><8A>E<86><A8><U+0001><U+000F><85><U+0005><U+0000><U+0000><U+0000><E9>2<U+0000><U+0000><U+0000>H<8B>E<C8>1ɉ<CA>H<F7>u<B8>H<83><FA><U+0000><U+000F><85><U+0004><U+0000><U+0000><U+0000><C6>E<DF><U+0000><E9><U+0000><U+0000><U+0000><U+0000>H<8B>E<B8>H<U+0005><U+0001><U+0000><U+0000><U+0000>H<89>E<B8><E9><A5><FF><FF><FF><F6>E<DF><U+0001><U+000F><84><B1><U+0000><U+0000><U+0000><8B>E<U+0603><C0><U+0001><89>E<B4><8B>E<B4><B9><U+0008><U+0000><U+0000><U+0000>H<F7><E1>@<U+000F><90><C6>H<C7><C1><FF><FF><FF><FF>H<U+000F>@<C1>H<89><C7>@<88>u<85><E8><U+0000><U+0000><U+0000><U+0000>H<89>E<A8><C7>E<A4><U+0000><U+0000><U+0000><U+0000><8B>E<A4>;E<D8><U+000F><83>(<U+0000><U+0000><U+0000>H<8B>EЋM<A4><89><CA>H<8B><U+0004><D0>H<8B>U<A8><8B>M<A4><89><CE>H<89><U+0004><F2><8B>E<A4><83><C0><U+0001><89>E<A4><E9><CC><FF><FF><FF>H<8B>E<C8>H<8B>M<A8><8B>U
<U+0609><D6>H<89><U+0004><F1>H<8B>E<D0>H<83><F8><U+0000>H<89><85>x<FF><FF><FF><U+000F><84><U+000F><U+0000><U+0000><U+0000>H<8B><85>x<FF><FF><FF>H<89><C7><E8><U+0000><U+0000><U+0000><U+0000>H<8B>E<A8>H<89>EЋM<B4><89>M<D8><E9><U+0000><U+0000><U+0000><U+0000>H<8B>E<C0>H<U+0005><U+0001><U+0000><U+0000><U+0000>H<89>E<C0><E9><A6><FE><FF><FF><C7>E<A0><U+0000><U+0000><U+0000><U+0000><8B>E<A0>;E<D8><U+000F><83>P<U+0000><U+0000><U+0000>H<8B>EЋM<A0><89><CA>H<83><<D0><U+0004><U+000F><85>)<U+0000><U+0000><U+0000>H<8B>E<D0>H<83><F8><U+0000>H<89><85>p<FF><FF><FF><U+000F><84><U+000F><U+0000><U+0000><U+0000>H<8B><85>p<FF><FF><FF>H<89><C7><E8><U+0000><U+0000><U+0000><U+0000><E9><U+0000><U+0000><U+0000><U+0000><E9><U+0000><U+0000><U+0000><U+0000><8B>E<A0><83><C0><U+0001><89>E<A0><E9><A4><FF><FF><FF><E8><U+0000><U+0000><U+0000><U+0000>H<89>E<98>H<8D>}<98>H<8D>u<E0><E8><U+0000><U+0000><U+0000><U+0000>H<89>E<88>H<8D>}<90>H<8D>u<88><E8><U+0000><U+0000><U+0000><U+0000>H<8B>E<90>H<89>E<E8>H<8D>}<E8><E8><U+0000><U+0000><U+0000><U+0000><F2><U+000F><U+0010>
^
Crunch.o:1:8: warning: null character ignored [-Wnull-character]
```

The AMD gpu is a Vega RX 56. I've installed the rocm drivers and dev packages from amd, and the device is shown by rocminfo and clinfo.

**Comment by illuhad** [comment]
No errors during compilation, these are warnings caused by the HIP headers, so it's AMD's job to fix them.
The second issue is because the compiler seems to interpret the .o files as source files, and tries to parse them. Separate compilation and linking stages properly and the issue should vanish. I suspect this is not actually a hipSYCL issue, since we just invoke clang with a few extra arguments and forward the user arguments to it. Likely the clang-10 that we ship will behave the same way in this situation.

**Comment by illuhad** [comment]
>  I've installed the rocm drivers and dev packages from amd
By the way: Unless you want to install the `rock-dkms` kernel driver there's no reason to install anything from AMD. hipSYCL comes with its own ROCm installation.

**Comment by cgleggett** [comment]
Thanks!

I have clang-9 installed (built locally from llvm git checkout w/ llvmorg-9.0.0 tag). Should I upgrade to clang-10?

**Comment by illuhad** [comment]
No, why? hipSYCL has its own clang installation in /opt/hipSYCL/llvm that it uses. This is a clang-10, so it's already using the latest clang.

**Comment by cgleggett** [comment]
Doing the linking step separately did the trick. Thanks.

It is interesting to note that the same SYCL code run on an AMD Vega 56 is about 40 times slower than when run on an NVidia GTX 1080Ti. This is relatively trivial code that finds primes. Also, it seems to lack the ability to run concurrent kernels. Is this expected?

**Comment by illuhad** [comment]
hm, so the 1080 Ti is in general a faster GPU than a Vega 56. Additionally, some algorithms run better on AMD and some on NVIDIA. Of course 40x performance loss is unexpected - there's probably an issue somewhere in the stack. Are you able to share your code?

At the moment, you will have to use several SYCL queues to run kernels concurrently (I'm currently working on a major rewrite of the scheduler such that this could eventually be done automatically). If this is the case for your program, it is a limitation at a lower level (ROCm runtime, driver, or hardware). I haven't done such tests on Vega 56, so I don't know what the expected behavior of the hardware is.

**Comment by illuhad** [comment]
From the compilation output you posted previously I see that you are not using `-O3` or other optimization flags. This could explain the performance of Vega 56. `syclcc-clang` behaves like a regular C++ compiler, i.e. unlike `nvcc` or `hipcc`, it does not add optimization flags by default.

**Comment by cgleggett** [comment]
That's interesting what you say about the queues - the Intel SYCL developers told me exactly the opposite, to share a single queue between all threads that are launching kernels.

wow, adding -O3 makes a **huge** difference. kernel execution speed decreases by about a factor of 100. 

I'll package up my example and post it when I have a few moments.

Can you recommend any kernel timing techniques since sycl::info::event_profiling stuff doesn't work?

**Comment by fodinabor** [comment]
did you really mean to say the speed _decreases_??

**Comment by illuhad** [comment]
> That's interesting what you say about the queues - the Intel SYCL developers told me exactly the opposite, to share a single queue between all threads that are launching kernels.

that's a bit of a different statement. I haven't said not to share queues between threads that submit kernels - in fact, this makes it easier and less error prone to program, so I would in general also second that statement.
However, if you want concurrent execution on hardware level, you need separate queues (which might then be shared among several submitting threads, if you like). The reason boils down to how stream objects work in the HIP/CUDA programming model.
In general, the question under what conditions the hardware executes kernels concurrently is outside the scope of the SYCL spec. It's entirely hardware/implementation-specific. So, in other words, it is entirely possible that Intel SYCL with their hardware has concurrent execution with a single queue - but that doesn't mean that it can generalized to other hardware or implementations. As I've said though, I'm working on some major changes that would also allow this to be possible with a single queue.

> Can you recommend any kernel timing techniques since sycl::info::event_profiling stuff doesn't work?

Since we use HIP/CUDA under the hood, you can use the regular AMD/NVIDIA profilers nvprof/nvvp and rocprofiler. I haven't yet tried to use rocprofiler though, so I'm not sure if it works with the ROCm version that we ship.
If you just want to know the runtime of some kernel you could also just do something along the lines of
```
auto t1 = some_time_measurement();
q.submit(...).wait();
auto t2 = some_time_measurement();
```

Also seconding @fodinabor's question - you likely meant the runtime decreases, right?

**Comment by cgleggett** [comment]
> wow, adding -O3 makes a **huge** difference. kernel execution speed decreases by about a factor of 100.

heh : kernel execution _time_ decreases by a factor of about 100.

**Comment by illuhad** [comment]
Excellent, that's great to hear :) You should find that for many applications, hipSYCL outperforms other SYCL implementations on GPUs :)

**Comment by cgleggett** [comment]
interestingly, adding the -O3 increases speed for a similar routine that executes on the CPU by only a factor of 1.5.

I noticed that when listing available devices via `sycl::platform::get_platforms()` I no longer see the host device. Which means I can only execute the SYCL kernel on a GPU. Is there a way to target the host device?

**Comment by illuhad** [comment]
> interestingly, adding the -O3 increases speed for a similar routine that executes on the CPU by only a factor of 1.5.

Different compilers/compiler backends can have varying optimization speedups when going to O3, so this sort of thing can happen.

> I noticed that when listing available devices via sycl::platform::get_platforms() I no longer see the host device. Which means I can only execute the SYCL kernel on a GPU. Is there a way to target the host device?

Currently, we have a static compilation model in hipSYCL, i.e. you decide at compile whether to run your code on AMD GPU, NVIDIA GPU, or CPU. This is because the HIP/CUDA programming model doesn't have a concept for different platforms like OpenCL does, so we would need an additional abstraction layer to decide at runtime whether to execute code on CPU or GPU. This is on the roadmap however and will be the next big thing after the redesign of the scheduler.
In order to compile for cpu, you will have to compile with `--hipsycl-platform=cpu`.

For good performance on CPU, I recommend using hierarchical or basic parallel for instead of ndrange parallel for - ndrange parallel for cannot be implemented efficiently on CPU for pure host library-based SYCL implementations (it's exactly the same for e.g. triSYCL).

**Comment by cgleggett** [comment]
> auto t1 = some_time_measurement();
> q.submit(...).wait();
> auto t2 = some_time_measurement();

the problem with doing this (at least when using intel's compiler) was that this does not give an accurate account of the kernel's actual run time, as a significant period of time can be spent between when the kernel is submitted, and when it's executed. This made it easy to see that even though all concurrent kernels were submitted at the same time, there was no actual concurrency.

**Comment by illuhad** [comment]
> the problem with doing this (at least when using intel's compiler) was that this does not give an accurate account of the kernel's actual run time, as a significant period of time can be spent between when the kernel is submitted, and when it's executed

the `wait()` should force the SYCL runtime to start processing stuff immediately. If your kernels are very small, you will see scheduling overheads, but in many cases it should work fine. I don't know what Intel SYCL is doing.
The best approach for profiling really is what hipSYCL is doing: Allowing you to use low-level hardware vendor profilers. `event_profiling` forces us to insert events into the HIP/CUDA stream after every kernel which can add significant overhead. Vendor profilers can give you better insights with very little overhead. This is also the reason why we haven't implemented `event_profiling` yet.

> kernels are submitted from separate std::threads (that are all started at the same time)

by the way, if you do this to achieve concurrent kernel execution, it likely won't help because SYCL executes kernels asynchronously. In other words, if you call `submit()`, you will in general be enqueuing stuff to some worker thread inside the SYCL runtime anyway, so it most likely won't matter from which thread the work comes.

> so far it doesn't look like any form of SYCL is doing concurrent kernel execution.

As I've said, it depends on the hardware, the implementation's backend (e.g. OpenCL implementations) and the SYCL implementation. I cannot comment on the conditions under which ComputeCpp and Intel SYCL will execute kernels concurrently. I can only tell you, that in hipSYCL this should work if the GPU supports it and you enqueue to several queues.
Additionally, dependencies between your kernels (e.g. accessing the same data) can force SYCL to order your kernels, in which case you will also not see concurrency. May I ask why this is so important to you? Do you have kernels that are so small that they will not fully utilize the GPU?

**Comment by cgleggett** [comment]
I'm investigating portability solutions that can target NVidia, Intel and AMD (eg Kokkos, Raja, OpenMP, hip, SyCL, etc). We have a multi-threaded framework running several million lines of code, and need to figure out how to offload some small fraction of tasks to GPUs. The level of intra-task concurrency is probably small enough that we would benefit from being able to schedule multiple kernels at once from different threads in order to fully utilize a GPU. If this turns out not to be achievable, then we will have to consider waiting until sufficient data has been accumulated before executing the kernels, which will require a significant refactoring of the framework. Right now I'm just playing with scheduling toys and models to understand how the various portablility solutions work, and how they interact with the hardware.
