### ISSUE TITLE
Which C++ standards are supported in device code?

### ISSUE THREAD

**Issue by invexed** [illuhad/hipSYCL#166]
First of all I'd just like to say thank you for this amazing project. I'm looking forward to testing it out.

Before I get too deep into researching SYCL, may I ask which C++ standards are supported in device code with the clang plugin and CUDA backend? I have a lot of C++17 device code (that currently compiles with clang) that I'm hoping to port to SYCL. Is that supported by hipSYCL?

**Comment by fodinabor** [comment]
As hipSYCL uses a mostly standard clang frontend and only adds modifiers to some functions, almost all C++ features, that are supported by Clang, should be supported in the device code as well.
I guess you're using Clang for your CUDA code already? Then I don't see any issues with using that code in hipSYCL.

**Comment by illuhad** [comment]
Thanks for your interest in the project! As @fodinabor says, C++17 should be no problem in principle. Of course, there are some restrictions on the allowed subset of C++ in SYCL device code, similarly to other heterogeneous programming models:
* nothing that requires runtime support like exceptions, new/delete, rtti, ... 
* recursion is not allowed by the SYCL spec in device code; cuda is a bit more forgiving here. While hipSYCL does allow the same constructs when compiling for nvidia GPU as CUDA, the AMDGPU LLVM backend has no concept of functions, so recursive code will most likely fail when compiling for AMD.
* The SYCL spec does not define how SYCL interacts with the STL; simple things like `std::plus` or static functionality (type traits and such) will work in device code, but in general it is hard to foresee if STL will work in device code because it depends on STL implementation which is beyond our control. For example, some STL implementations may incorrectly pull in SSE intrinsics or similar for some headers which will of course fail in device code.

There's one additional caveat: Since the hipSYCL headers require at least C++14, the `syclcc-clang` compiler wrappers pass `-std=c++14` to clang to enforce a standard that can compile our header files. From playing around it seems that clang will use the standard that is the last one on the command line - in this case we will most likely be fine if the user additionally sets the standard.

@sbalint98, can you please investigate how a proper solution could look like? Maybe we can add a mechanism in `syclcc-clang` to only add `-std=c++14` if no other, newer standard has been specified (which might be a good idea anyway)?

Until we have fixed this on the master branch, you can just manually replace the `-std=c++14` in `bin/syclcc-clang` for your experimentation if it turns out to be an issue - it should be easy with find/replace :)

**Comment by invexed** [comment]
Thank you both for your answers. It's great to hear that all of the C++ features Clang supports are also supported by hipSYCL; there really is no reason to prefer CUDA now! The source of the confusion was that I read somewhere that the current SYCL spec only supports C++11 in device code. I presume this is an instance where hipSYCL (thankfully) does not conform to the standard.

Would you like me to leave this issue open for resolving the ```-std=c++14``` flag quirk?

**Comment by illuhad** [comment]
The SYCL 1.2.1 spec indeed builds on C++11 - but there's no reason to forbid implementations to (optionally) allow more modern features. I think the intent is rather that a SYCL programmer is guaranteed that at least C++11 is supported by all SYCL implementations. At least that's my interpretation :)

Yes, please leave this issue open - we will close it once we have fixed the `-std=c++14` issue.

**Comment by illuhad** [comment]
`-std=c++14` quirk has been fixed by PR #168 - please reopen if it turns out that there's an issue with the current implementation.
