### ISSUE TITLE
atomics on CPU

### ISSUE THREAD

**Issue by mrzv** [illuhad/hipSYCL#172]
I have the following simple atomic counter example that compiles and runs fine for CUDA, but doesn't compile on the CPU.
```
#include <iostream>
#include <CL/sycl.hpp>

namespace s = cl::sycl;

int main()
{
    s::queue q;

    int counter = 0;
    {
        s::buffer<int> counter_buf(&counter, 1);

        q.submit([&](cl::sycl::handler& cgh)
        {
            auto access_counter = counter_buf.get_access<cl::sycl::access::mode::read_write>(cgh);

            cgh.parallel_for<class atomic_increment>(s::range<1>(1 << 30), [=] (cl::sycl::id<1> tid)
            {
                s::atomic<int> atomic_counter { s::global_ptr<int> {&access_counter[0]} };
                atomic_counter.fetch_add(1);
            });
        });
    }

    std::cout << "Counter: " << counter << std::endl;
}
```

```
/opt/hipSYCL/CUDA/bin/syclcc-clang --hipsycl-gpu-arch=sm_52 -O3 atomic-counter.cpp -o atomic-counter-cuda
```
compiles and runs fine.

```
/opt/hipSYCL/CUDA/bin/syclcc-clang --hipsycl-platform=cpu -g atomic-counter.cpp -o atomic-counter-cpu
In file included from atomic-counter.cpp:3:
In file included from /opt/hipSYCL/CUDA/bin/../include/CL/sycl.hpp:58:
/opt/hipSYCL/CUDA/bin/../include/CL/sycl/atomic.hpp:103:12: error: use of undeclared identifier 'atomicAdd'
    return atomicAdd(_ptr, operand);
           ^
atomic-counter.cpp:23:32: note: in instantiation of function template specialization 'cl::sycl::atomic<int, cl::sycl::access::address_space::global_space>::fetch_add<int, nullptr>' requested here
                atomic_counter.fetch_add(1);
```

I know atomics are not fully supported (they are listed as a limitation in README), but other issues suggest that only minor features of atomics are missing. Is the above error by design, or is it something that can be easily fixed?

**Comment by illuhad** [comment]
Hi, I believe this error can be fixed easily. It comes from the fact that hipCPU (the library we use to emulate the HIP runtime API on CPU) does not yet implement the CUDA atomic functions, in this case `atomicAdd()`. This implementation should be relatively straight forward by mapping CUDA atomics to standard C++ atomics. If you want to work on it, I'd happily merge a PR :)

Note: In the long-term, the plan is to deprecate hipCPU altogether as it is an additional abstraction layer that is not necessary in principle on CPU. But this will still take some time, so improving hipCPU still makes sense.

**Comment by mrzv** [comment]
I see. I assume you want the PR in [hipCPU repo](https://github.com/illuhad/hipCPU)?

Also, why deprecate hipCPU? It's incredibly convenient to have one codebase that works both on the GPU and the CPU. Or is the point that other SYCL implementations will take care of the CPU? Which ones do you recommend?

**Comment by illuhad** [comment]
Yes, we will probably need both a PR in hipCPU to add the new code and a PR in hipSYCL to bump the hipCPU git submodule to the new commit version.

By deprecating hipCPU I did not mean to deprecate CPU support in hipSYCL. On the contrary, the plan is to improve support for non-HIP or non-GPU targets in the future. In particular, I want to enable runtime device selection where at the moment it is necessary to decide at compile time which device to target. One major obstacle to overcome is that hipSYCL is hardcoded at the moment to use the HIP runtime API (hence the need for hipCPU). Since the HIP runtime is a collection of global functions, there is now way to compile both against hipCPU and GPU HIP at the same time without name collisions.

As a solution I am at the moment developing an entirely new hipSYCL runtime, which will (among many other new features) bring a generic backend interface based on abstract classes/virtual functions for the runtime functions. This will allow us to add regular GPU HIP backends, CPU backends without having to emulate the HIP API and potentially even other backends such as OpenACC or targeted OpenMP.
What is not yet solved by this new runtime will be the kernel headers which would also need dedicated CPU implementations to get rid of hipCPU (for example, for atomics). This is why I expect that the deprecation of hipCPU will still take some time.

**Comment by mrzv** [comment]
Ah, fantastic. Thanks for explaining.

**Comment by mrzv** [comment]
I started looking into this, and immediately ran into a problem. Atomics in C++11 and C11 have this design "feature" that they must be declared as appropriate types. In particular, you cannot cary out atomic operations on non-atomic types. In SYCL, as far as I can tell, `atomic` is just a wrapper around a pointer to a regular type. So there is a problem. I don't know how to solve this short of unsafe casting that leads to UB. Do you have ideas what the right way to do this is?

**Comment by illuhad** [comment]
it seems this is one of the cases where it's difficult to force the HIP/CUDA model into C++.. If it cannot be done with pure C++, you can also use OpenMP since we use it on CPU anyway, i.e. `#pragma omp atomic`.
I've just had a quick look at the triSYCL code to see how they have implemented it on CPU, but it seems they don't have atomic support at all.

**Comment by mrzv** [comment]
There are also [GCC extensions](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fsync-Builtins.html), like `__sync_fetch_and_add`, which Clang also seems to support. I just tried, and it just works. Would that be a better route? (I have no experience with OpenMP, so I'm a little hesitant.)

**Comment by mrzv** [comment]
Or better [`__atomic` functions](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html#g_t_005f_005fatomic-Builtins), since `__sync` seems to be deprecated.

**Comment by mrzv** [comment]
`contrib/HIP/include/hip/hcc_detail/hip_atomic.h` seems to have the right functions already. Any way to just enable these on the CPU?

**Comment by illuhad** [comment]
I would prefer OpenMP, since
* we use OpenMP for multithreading, so it makes sense to also use it for synchronization (when mixing different frameworks, it's not always clear how they interact)
* there may be some interest in using non-gcc/non-clang OpenMP compilers on CPU, such as the Intel compiler

I don't think we can use `contrib/HIP/include/hip/hcc_detail/hip_atomic.h` - this file is part of the AMD ROCm headers for GPUs.

**Comment by mrzv** [comment]
I can't seem to find if it's possible to implement atomic CAS with OpenMP. Do you know by chance?

**Comment by illuhad** [comment]
It may be that CAS is too low level for the way that OpenMP is usually employed, however it can probably be (inefficiently) emulated with `omp critical`. We could additionally add optimized code paths when compiling with clang or gcc that use `__atomic` compiler builtins.

**Comment by keryell** [comment]
> it seems this is one of the cases where it's difficult to force the HIP/CUDA model into C++.. If it cannot be done with pure C++, you can also use OpenMP since we use it on CPU anyway, i.e. `#pragma omp atomic`.
> I've just had a quick look at the triSYCL code to see how they have implemented it on CPU, but it seems they don't have atomic support at all.

Yes, it is not implemented in triSYCL. If it was, it would just use normal C++ atomic on CPU and another runtime when compiled with the device compiler to target non-host code.

**Comment by mrzv** [comment]
@keryell How can you make C++ atomics work with the SYCL model? C++ doesn't have a way of performing atomic operations on memory that wasn't declared atomic from the start. It also doesn't have a way of performing atomic and non-atomic operations on the same memory. At least, not that I know of. I think there was a C++20 proposal on this topic, but I don't know if it made it in.

**Comment by keryell** [comment]
In SYCL 1.2.1 you need to use the `atomic` access mode in the `buffer` `accessor`.
So you could copy the data into a buffer of `std::atomic<value_type>` before using it on CPU. :-)

In a real implementation or to go beyond pure SYCL 1.2.1, yes, you should use C++20 `std::atomic_ref` or at least steal the implementation if you do not use C++20 and probably tweak the buffer alignment if some atomics require some special alignment...
In the case your CPU does not provide atomic for a given type (the 4-bit CPU of my dish-washer?), you can use 1 global lock per buffer up to 1 lock per buffer element, according to your performance requirement. :-/ In that case the implementation with `std::atomic` as a starting point would not help either and `std::atomic_ref` would not be more efficient...
Or a simpler case: use sequential kernel execution on CPU when using non supported atomic types... :-)
So at the end, I am unsure it is a real problem on some common hardware used in HPC systems for SYCL-supported atomic datatypes (which are up to 64 bits only)...

**Comment by mrzv** [comment]
> In SYCL 1.2.1 you need to use the atomic access mode in the buffer accessor.

Sorry, I'm new to SYCL and this confuses me. Is the following code snippet from the first comment on this issue not legal SYCL?
```
auto access_counter = counter_buf.get_access<cl::sycl::access::mode::read_write>(cgh);
s::atomic<int> atomic_counter { s::global_ptr<int> {&access_counter[0]} };
```

The rest of your points are well-taken. Your dish-washer is an especially troubling use case. ;-)

**Comment by illuhad** [comment]
The spec says (e.g. in section 3.5.2.3) that atomic access is only guaranteed to work if the buffer access mode is `atomic`. In this case, a solution that wraps all elements in an `std::atomic` is possible as pointed out by @keryell . However, not only will this be likely inefficient, (which is why I have never considered such an implementation for hipSYCL), I would also agree that the spec is at the very least misleading at the moment since the `atomic` constructor that you mention strongly suggests being able to use arbitrary memory locations and there is no note in the spec that this constructor is only valid if the memory used in this constructor comes from a buffer with `atomic` access mode.

So, going forward I would still say that I'd strongly prefer an implementation that can do atomic operations on arbitrary memory locations as you assumed. Not only will this be faster, it will also be what people expect regarding performance implications and a better model for the future evolution of SYCL in my opinion.

**Comment by mrzv** [comment]
Thanks for the explanation. Sounds like something the committee needs to straighten out. It would be terrible if different implementations interpreted this differently.

Is `atomic` buffer access mode supported in hipSYCL? Or not yet? I just tried changing `read_write` to `atomic` in the above example, and it complained. It looks like the accessors are not implemented.

**Comment by illuhad** [comment]
Atomic accessors are not yet implemented. There may be some code related to it, but most of it is a stub since the strategy regarding atomics has always been to allow atomics on arbitrary memory locations in which case the `atomic` access mode can simply be treated as a regular `read_write` access mode. This solution would be more general than what the standard currently allows, and, as I've said, more in line with what is useful for performance and user expectations.

**Comment by jeffhammond** [comment]
@mrzv I can help you with the CPU atomics implementation if you want. You are right that OpenMP does not have CAS yet.  I recommend using `__atomic` intrinsics.  They are widely portable.

**Comment by mrzv** [comment]
@jeffhammond I got discouraged by @illuhad's [comment](https://github.com/illuhad/hipSYCL/issues/172#issuecomment-560163581) about moving away from hipCPU to a different runtime. It seems wasteful to add atomics to hipCPU, if it will go away soon anyway. (I am very much looking forward to the new runtime, however.)

**Comment by illuhad** [comment]
@mrzv The new runtime is kind of orthogonal to this issue. A SYCL implementation usually consists of three parts:
* A compiler component
* The runtime (e.g. scheduler)
* The kernel headers that implement e.g. math functions.

Extending the `atomic` class is a pure kernel header thing, and should therefore not depend on changes to the runtime. There's only one thing to keep in mind: The current implementation of `atomic` just calls HIP functions that are implemented on CPU by hipCPU. The implementation of CPU atomics should therefore be done directly in the `atomic` class since hipCPU will be removed at some point.

**Comment by mrzv** [comment]
@illuhad Ah, I see. So the comments above about hipCPU are irrelevant. The changes should be done directly in hipSYCL?

**Comment by illuhad** [comment]
@mrzv Yes, thanks for the PR :smile:
