### ISSUE TITLE
malloc() works inside sycl kernel ?? !!

### ISSUE THREAD

**Issue by Alkeryn** [illuhad/hipSYCL#182]
so i have the following code as an example 
```cpp
cl::sycl::buffer<int*,1> pointbuff(1);

myqueue.submit([&](cl::sycl::handler& cgh) {
	auto p = pointbuff.get_access<access::mode::read_write>(cgh);

	cgh.single_task<class test>([=](){
		p[0] = (int*)malloc(sizeof(int));
		});
	});
```
what i don't understand is that it works so i'm wondering by what kind of wizardry it does.
also build with computecpp.

i'm very surprised by this as malloc dosen't work in opencl kernels so kinda confused lol.

**Comment by illuhad** [comment]
I don't know why it works with ComputeCpp. As far as hipSYCL is concerned: You are experiencing the advantages of the hipSYCL approach of building on established vendor-supported toolchains. In hipSYCL, we are in effect using a HIP/CUDA compiler (with a frontend that has been augmented to also understand SYCL code) when compiling for device. This means you can do anything in hipSYCL that you can also so in CUDA. Since CUDA supports malloc() in device code, it also works in hipSYCL :)

**Comment by Alkeryn** [comment]
Yea this is kinda cool ^
but i'm legit confused by what kind of wizardry it works under computecpp's compiler (the one that comes with the oneapi toolchain)
it isn't suposed to work as the implementation is over opencl, legit i'm lost rn lol
because it actually work and the data isn't lost wth lol.

**Comment by Alkeryn** [comment]
Well the data can only be accesed from gpu code as the accesor won't dereference gpu pointers which make sense, but i legit have no idea how it can even work on the opencl backend, it don't make sense lol

well i really wanted to be able  to malloc in kernel so that's cool i guess but what is weird is that the sycl spec don't even mention malloc so this is weird that it is working ^

**Comment by Alkeryn** [comment]
On a side note, man your software is great, i'm really having fun with my gpu rn ^

**Comment by illuhad** [comment]
the one that comes with oneAPI? So, you mean Intel LLVM SYCL? That's a different implementation, not ComputeCpp ;) 
I suppose questions concerning other implementations are better answered by them. Maybe they have deliberately put in some malloc support.
Thanks for the compliment, that's very motivating :)

**Comment by fodinabor** [comment]
Are you using the PTX Backend of ComputeCpp to target your GPU? It might be using a similar approach as hipSYCL, as it generates actual Nvidia assembler, which might enable malloc as well.

18.12.2019 00:13:16 Alkeryn <notifications@github.com>:

**Comment by Alkeryn** [comment]
Oh i thought oneapi used computecpp's implementation
also nvm i'm pretty tired i didn't realised it didn't recompile on the few test i made

so you can do malloc() on intel's oneapi implementation but you can't use it in a different kernel run so it is kind of useless

still pretty cool that you can do it on hipsycl implementation but as i want my code to stay portable i guess i won't use that feature ^

**Comment by illuhad** [comment]
@Alkeryn, no, ComputeCpp is Codeplay's (proprietary) SYCL implementation. Intel's SYCL implementation is just called Intel SYCL or clang/LLVM SYCL since it's supposed to go into mainline clang at some point. Thanks for the solution to this mystery :) I suspect they probably started adding in support but aren't done yet (?)

@fodinabor, I think it's a different approach:
* afaik, they compile to PTX but inject ptx into OpenCL since NVIDIA OpenCL supports ptx kernel ingestion
* even if they injected PTX into CUDA instead of OpenCL (which would be the next closer step to what we do), they still use a pure SYCL frontend which will not allow the same interoperability as we do (e.g. you will probably not be able to use CUDA intrinsics etc)

So, I would still be surprised if malloc() works in ComputeCpp.

**Comment by Alkeryn** [comment]
i wonder if there is a way to implement a portable malloc on sycl tho, as that would be pretty cool, i have few algos i'd like to port to sycl but switching from dynamic containers to fixed sized ones don't really feel elegant haha

**Comment by illuhad** [comment]
I don't think this can be done in SYCL 1.2.1, at least not in the way you would like with allocations persistent across multiple kernel launches.
The problem is that in SYCL 1.2.1 (like in OpenCL 1.2) it is not guaranteed that memory addresses are consistent across several kernel launches. For example, the memory address of  the first element of an accessor to the same buffer may vary across different kernel launches (It would be inefficient, but in principle the SYCL runtime could decide to discard the old data buffer and copy the data to a new buffer before the kernel launch).
Without consistent memory addresses, we cannot implement such a `malloc()` function. This problem is gone when Intel's USM proposal ends up in the spec. Then we can have pointers as well as unified memory across host and device and a portable malloc() could be implemented using only what's in the SYCL spec.

In general, I would however discourage using dynamic memory allocation in kernels as it is usually inefficient on GPUs. So, if possible, it may make sense for performance for you to get rid of the dynamic containers :)

**Comment by keryell** [comment]
I suspect what you experience is that you run your kernel on CPU (i.e. using the host device), so it just does work as usual. Usually I do graphics inside kernels as a debugging tool on host device. This is why I love SYCL: we can debug on host first with normal host code and normal debugger before switching later on a different accelerator.
