### ISSUE TITLE
Queue constructor requires optional argument

### ISSUE THREAD

**Issue by tomdeakin** [illuhad/hipSYCL#185]
This constructor requires that a `property_list` is passed, even though it should be optional due to the default value:
```
    queue(const device_selector &deviceSelector,
        const async_handler &asyncHandler, const property_list &propList = {});
```

For example, the following queue creation did not compile for me:
```
  cl::sycl::queue *queue = new cl::sycl::queue(dev, [&](cl::sycl::exception_list l)
  {
    // omitted ...   
  }); 
```

I can make it compile by added an empty property list at the end:
```
  cl::sycl::queue *queue = new cl::sycl::queue(dev, [&](cl::sycl::exception_list l)
  {
      // omitted ...   
  }, {});
```

**Comment by illuhad** [comment]
Hi Tom,

thanks for reporting. The constructor in question exists. However, it seems that two of the constructor overloads, if invoked in the way as in your example, are ambiguous:
```
cl::sycl::queue::queue(const cl::sycl::device_selector&, const async_handler&, const cl::sycl::property_list& = {})
cl::sycl::queue::queue(const cl::sycl::device_selector&, const cl::sycl::property_list&)’
```
so, something like this will work:
```
cl::sycl::queue *queue = new cl::sycl::queue(dev, cl::sycl::async_handler{[&](cl::sycl::exception_list l)
  {
    // omitted ...   
  }}); 
```
which is admittedly a bit ugly.

The reason seems to be that the spec requires `property_list` to have a variadic template constructor, so the compiler could also instantiate the property list constructor with the async handler lambda as argument.

I feel that ideally, *something* here should be an `explicit` constructor. I've just rechecked the spec and it seems that it does not make any requirements here, so in principle it could be argued that the current behavior is covered by the spec being ambiguous here.

However, since the root cause is the template constructor from `property_list` accepting arbitrary types which does not really make sense semantically (it only makes sense with properties), I would suggest that we remove the `property_list` constructor from overload resolution with some SFINAE trickery if the argument(s) are not valid properties.
Some research reveals that this is also exactly how [triSYCL behaves](https://github.com/triSYCL/triSYCL/blob/dc50058eb5d83b8cdddd6a43c994f76ea04a8b0e/include/triSYCL/property_list.hpp#L44), so this change would bring hipSYCL in line with the other implementations. But again, I don't feel that this behavior is strictly mandated by the current spec which also doesn't seem to impose any requirements on the `property_list` constructor, so we should also clarify the spec here.

**Comment by tomdeakin** [comment]
Ah I see, that's unfortunate!
Shall I raise an issue in the spec?

**Comment by illuhad** [comment]
That would be great, thank you :) As this is purely a maintenance issue, you can use the public github repository: http://github.com/KhronosGroup/SYCL-Docs

**Comment by tomdeakin** [comment]
For cross-referencing later, it's here: https://github.com/KhronosGroup/SYCL-Docs/issues/66

**Comment by tomdeakin** [comment]
Closing due to SYCL 1.2.1 spec updates.
