### ISSUE TITLE
Tools for Profiling

### ISSUE THREAD

**Issue by jon-chuang** [illuhad/hipSYCL#189]
I am wondering about whether tools for profiling, for instant NVIDIA's nsight, including NVTX, will work. Since hipSYCL generates HIP code and the HIP frontend uses the CUDA compiler. However, when using NVIDIA nsight with a hipSYCL compiled program, I do not receive any information about CUDA apart from a CUDA stream API call.

**Comment by illuhad** [comment]
Yes, it does work with nvidia profilers. From the point of view of the NVIDIA tools, a hipSYCL program is indistinguishable from any other CUDA program. I've used NVIDIA's tools routinely with hipSYCL. I'm not sure why you don't receive information in the tools - maybe the kernel is not actually submitted to CUDA by hipSYCL because nothing depends on it, and no explicit synchronization was requested by the code?

**Comment by jon-chuang** [comment]
Hi Aksel, turns out it was because my data sizes were too small for the kernel calls be registered as events. Fixed with larger data sizes.
