### ISSUE TITLE
Compatibility of syclcc-clang with CMake Projects?

### ISSUE THREAD

**Issue by jon-chuang** [illuhad/hipSYCL#190]
I am trying to build CMake projects with syclcc-clang selected as the compiler. However, I have been encountering several errors. The one I am now stuck on is the following:
```
/data/CLion-2019.3.2/clion-2019.3.2/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/lib/llvm-9/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/bin/syclcc-clang -G "CodeBlocks - Unix Makefiles" /home/jonch/CLionProjects/Multigrid

Cannot get compiler information:
	Compiler exited with error code 255: /usr/local/bin/syclcc-clang -xc++ --hipsycl-gpu-arch=sm_61 --cuda-path=/usr/local/cuda-10.0 -std=gnu++14 -fpch-preprocess -v -dD -E
```
Previously, I solved the following with `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__STRICT_ANSI__")`.
```
/data/CLion-2019.3.2/clion-2019.3.2/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/lib/llvm-9/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/bin/syclcc-clang -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 -DWITH_CUDA_BACKEND=TRUE -G "CodeBlocks - Unix Makefiles" /home/jonch/CLionProjects/Multigrid
...
/usr/local/bin/syclcc-clang    --hipsycl-gpu-arch=sm_61    -std=gnu++14 -o CMakeFiles/cmTC_97289.dir/testCXXCompiler.cxx.o -c /home/jonch/CLionProjects/Multigrid/cmake-build-debug/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
...
In file included from <built-in>:1:
    In file included from /usr/lib/llvm-9/lib/clang/9.0.1/include/__clang_cuda_runtime_wrapper.h:36:
    In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/cmath:47:
    /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/std_abs.h:102:7: error: __float128 is not supported on this target
      abs(__float128 __x)
          ^
    /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/std_abs.h:101:3: error: __float128 is not supported on this target
      __float128
```

Here is my CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --hipsycl-gpu-arch=sm_61")

project(Multigrid)

add_executable(Multigrid main.cpp)
```
Clang 9, CMake 3.15.3, Ubuntu 18.04
Problem persists when upgrading from GCC 7.4 to GCC 9

**Comment by illuhad** [comment]
Hi, 

yes, there is cmake integration (see the cmake directory). Pinging the authors @psalz @VileLasagna  of the glorious hipSYCL cmake integration, as they can provide more details.

I've never seen this issue before (even with cmake) but the compiler invocation that you show
```
/usr/local/bin/syclcc-clang -xc++
```
is a recipe for failure since `-xc++` forces clang to compile in regular C++ mode, whereas `syclcc` tries to get it to compile in HIP/CUDA mode when compiling for GPU.

If you are compiling for GPU, gcc is not involved at all (apart from maybe providing some headers), so upgrading won't help. That `__float128` issue may be related to compiling with `gnu++14` instead of `c++14`. It's a clang CUDA toolchain issue. I think you can tell cmake to use regular C++14 using `set(CMAKE_CXX_EXTENSIONS OFF) ` to disable GNU extensions.

The "clean" way to use hipSYCL in cmake projects is to use the `add_sycl_to_target()` function from the hipSYCL cmake integration. The same function is also provided by ComputeCpp and triSYCL, allowing easy transitions between these SYCL implementations.

**Comment by jon-chuang** [comment]
It appears cmake works only when I run from command line. I believe it's because my editor CLion, runs some additional tests that the sycl compiler can't pass. In any case, there's an easy work around, so I'm closing.

**Comment by jon-chuang** [comment]
By the way, with `__STRICT_ANSI__`, does this mean that I won't be able to emulate 128 bit integer operations on my GPU?

**Comment by illuhad** [comment]
I'm not even sure if 128 bit integers, even if emulated, are supported for any CPU target? I'm not sure if this would work on CUDA (or HIP) since I would expect these operations to be very target specific and arguably be implemented with some intrinsics that are not available on GPU.

**Comment by VileLasagna** [comment]
A more elegant way of doing this is by adding 
`set(CMAKE_CXX_EXTENSIONS OFF)`

Effectively what this does is change that `-std=gnu++14` to `-std=c++14`. this removes some of GCC's std lib extensions which are not supported by some other compilers (one that always gives me grief in this direction is NVCC)
