### ISSUE TITLE
Automatic kernel fusion?

### ISSUE THREAD

**Issue by jon-chuang** [illuhad/hipSYCL#191]
Is the asynchronous task graph powerful enough to enable the possibility of automatic kernel fusion in the future?

**Comment by illuhad** [comment]
This is something I plan on investigating in the future, at least for certain kernel invocations (in particular `single_task`) and special cases. But I am skeptical that this will be anything more than "experimental research" quality. Since this is something that needs to be done at runtime, a production solution would likely require a common IR for all involved devices (e.g., CPU and GPU) and runtime mechanisms for relinking and recompiling. We are very far away from that. I'm also not sure if you would want such a complex feature in a general purpose SYCL implementation since I would expect the decision making whether to fuse kernels to cause considerable overheads.
As far as I know, other popular programming models like CUDA or OpenCL don't have built-in support for this either (It's added at a higher level through frameworks like Tensorflow that are far too complex for me to reinvent ;) ).
Now what can be done (and will be done at some point by the new hipSYCL runtime that is currently in development) is fusing data transfers of kernels that require adjacent memory regions.

What use cases exactly are you looking at? Because it's based on modern C++, SYCL can easily support composable kernels, e.g. with templates and lambda functions.

**Comment by jon-chuang** [comment]
By fusing data transfers, do you mean from the host to device?

What do you mean by composable kernels? Is there a reference for this?

**Comment by illuhad** [comment]
> By fusing data transfers, do you mean from the host to device?

host to device, device to host or device to device.

> What do you mean by composable kernels? Is there a reference for this?

Sure. In the simplest case it can refer to customizable algorithms (think for example of STL algorithms that accept lambda function e.g. as comparators). More sophisticated applications would be e.g. expression templates (there's a wikipedia page on that).
Here are some GPU specific slides, focusing on C++ ranges: https://michel.steuwer.info/files/talks/2017/SPLS-2017.pdf
Note that what they do does not require any new compiler features, it just exploits what's possible in C++.

**Comment by fodinabor** [comment]
I also only know the term _kernel fusion_ from specialized implementations on top of CUDA/OpenCL/..

For example in an image processing context it might make sense to combine filter masks and only filter an image once, but this is very specific to your application and will probably never be supported by any _low-level_ offloading API.
For image processing you might look into OpenVX for example (OpenVINO, MIVisionX or VisionWorks are implementations).

The only thing that can be done (what hipSYCL will be capable of soonish or CUDA's graph implementation also do) is optimizing data transfers by analzying their usage in the kernels and avoiding to copy data twice, as illuhad already mentioned.

**Comment by jon-chuang** [comment]
It seems however possible that two kernels slated to be applied sequentially which have a direct read-write dependency, and that intermediate device side buffer is written to by the kernel, one can remove the intermediate write operations.

**Comment by jon-chuang** [comment]
From what I understand, this is the primary purpose of kernel fusion, at least in the deep learning context

**Comment by illuhad** [comment]
Yes. The idea is to merge kernels to also avoid storing data in memory just to load it again in the next kernel. However, I think there's a crucial difference: In e.g. deep learning frameworks, the set of kernels is finite and well known and the memory access patterns of those kernels are well known. So, removing those loads and stores is relatively easy because the framework knows how to adapt each individual kernel. In a SYCL implementation, the kernel is provided by the user and can be arbitrary. I think this is a much more complex scenario, because we have no idea about memory access patterns, how registers map to writes/reads and how to efficiently merge those kernels. This would probably require some very complicated analysis techniques by the compiler which may or may not work in the general case.

If kernel fusion at compile time is sufficient for you, you can build an expression template system on top of SYCL as I had mentioned earlier, by simply using what C++ gives you already.

**Comment by illuhad** [comment]
Closing since this is not really an issue to be solved at the level of a SYCL implementation.
