### ISSUE TITLE
Fully support syclcc in CMake

### ISSUE THREAD

**Issue by psalz** [illuhad/hipSYCL#21]
I’ve been trying to make hipSYCL work with a more “complex” CMake setup than what is used for the tests, in particular, one that finds and links other libraries (standard CMake stuff, really). I did manage to get it working, however not without some changes.

Right now there's a couple of issues as far as I can tell:

The most pressing one is the in-source temporary files. CMake often uses `try_compile` for feature detection or to determine a library version. For example, the `FindMPI` module compiles a small program to see if a particular library it found actually works. The problem is that these files are often located somewhere in a read-only location (if it’s a system installation), so `syclcc` cannot write its temporaries and the `find_package` call simply fails (and the reason is not particularly well communicated by CMake).

Now within `syclcc` you [remarked](https://github.com/illuhad/hipSYCL/blob/191fa6c208ab3961c1e9d76e9ebdaffda39c7170/bin/syclcc#L176) that temporaries are located in-source for more robust include resolution, however so far I’ve had no problems with out-of-source builds. Maybe this could be made configurable through a CLI parameter? In any case I think writing into the source tree is a bit hairy and should best be avoided, at least by default.

Another thing is compiler detection. The very first thing CMake does is to compile a small program (however this time within the local `CMakeTmp` folder) to try and determine the compiler version. Right now this identifies `nvcc` as `gcc`, since (afaik) that is the default host compiler of `nvcc`. I’m not sure what the implications of this are, i.e. if there is any difference in parameters that will be passed to `syclcc`, e.g. something `gcc`-specific, which could then maybe interfere with the Clang preprocessing passes. As an aside, and to alleviate this, it might be worth considering setting the host compiler of `nvcc` to Clang by default, which would fit better with the rest of the compilation stages anyway, as they are all LLVM-based.

In addition to these points, if `/tmp` is a `tmpfs` mount, compilation performance could also be greatly improved by moving all temporaries there.

Finally, something that might be worth investigating is to provide a CMake function like ComputeCpp's `add_sycl_to_target`, as [provided by their SDK](https://github.com/codeplaysoftware/computecpp-sdk/blob/163fdf3b952873aa17d49492ce317f462042d026/cmake/Modules/FindComputeCpp.cmake#L380). I see several benefits to this:
-	First it would allow to only compile certain translation units with the device compiler. For larger projects this could really cut down on compilation times.
-	Secondly, this would improve compatibility with existing projects that work with ComputeCpp. 
-	This could also make the specification of rewrite paths -- as proposed in #20 --  more convenient, as instead of adding a CLI parameter this could be done through an additional parameter for `add_sycl_to_target`.

**Comment by illuhad** [comment]
It's possible that the reason why in-source builds appeared more robust to me was the bug that you fixed in PR #13 which caused builds to fail unless they were in-source. Also, before I was using clang's inclusion rewriter, I tried only rewriting those files (and their including "parents) where actually something was changed. With this approach, it was more important to remain in the same directory since it could be that some files in the in the project were not rewritten. With the current implementation, we could certainly try again having the `syclcc` temporary files in `/tmp`.
With the planned selective rewriting, i.e. issue #20, if a user doesn't rewrite all files of his project, compiling in '/tmp' will likely fail. This can likely be fixed by passing the original directory of the file as include directory to the compiler.

There's another minor issue that we should care about: The rewrite step at the moment produces files named `originalfilename.inc.cpp`. So, if we have several compilation processes at the same time with files of the same name (but in a different directory), we will have name clashes if the temporaries are all in `/tmp`. To fix this, we need to add a unique id to the filename, as is done with the result of `hipsycl_transform_source`. Alternatively, we could also create a temporary directory with unique name for the compilation of each source file, and put our temporaries there.

I agree with setting the host compiler of nvcc to clang, although this is likely of less priority if we use clang as default cuda compiler anyway.

In general I fully agree that it would be nice to have better CMake support for hipSYCL, in particular being able to find hipSYCL with cmake would be really cool. I can see the use of `add_sycl_to_target`, in particular because not only ComputeCpp has it, triSYCL seems to [have it as well](https://github.com/triSYCL/triSYCL/blob/a699105033cb78ce74556fb82caa51b456b5ca8f/cmake/FindTriSYCL.cmake#L209), although it's probably not one of my personal priorities. So, if you want to have it, I'll gladly merge a pull request :)

**Comment by VileLasagna** [comment]
Hello there

I'm currently giving hipSYCL a go myself and I'm quite interested in this. Is any of you working towards any sort of implementation of this? I could have a go at writing some very basic find scripts on top of which we could start building upon if not.

**Comment by illuhad** [comment]
It's at the moment not one of my priorities, but I'd love to merge a pull request and see this working if you want to have a go at it :)

**Comment by VileLasagna** [comment]
I'll see if I can get something usable started in the next couple of weeks or so. Just had a kind of fiddly time getting my first example to build so, it's prime time for these niggles to be fresh in the mind. One of them, though, is something I want to understand the reason why before I put it in the change (if there's any particular one):

`syclcc` tries to suss out your backend through the `HIPSYCL_PLATFORM` environment variable but it alternatively takes a parameter so you can specify. If you do pass something there, though, and it DOES find the variable (say if you added your default to your bash profile), syclcc just nopes out. Is there any particular reason why it doesn't treat the parameter as an override instead of just exiting? That's the behaviour I expect (and this ties in because one of the things would have to be specifying the backend through a cmake cache variable)

**Comment by illuhad** [comment]
Originally, there was only the environment variable. Later, when I added the CPU backend and needed to easily specify which backend to compile for in the cmake file of `libhipSYCL`, the command line variable was added. At the time, since I didn't want to worry about what overrides what and how to document such behavior clearly, it was decided that only either one of those two ways of specifying the platform could be set.
If you say that it's counterintuitive or makes implementing proper cmake support harder, feel free to change this behavior. It has bitten me as well sometimes ;)

**Comment by psalz** [comment]
Back when I implemented Clang-CUDA support into `sylcc` I did a quick survey at my office about whether an environment variable should take precedence over a CLI parameter or the other way round -- turns out the opinions differ :). That being said, `--cuda-clang-compiler` currently takes precedence over `HIPSYCL_CUDA_CLANG_COMPILER`, which is in line with what you're suggesting. In any case we should be consistent!

As mentioned in the original post I actually have a working CMake setup for my local experiments right now, but it's still a bit of a mess and needs cleanup before it can be upstreamed (and I'm still busy with unit tests - I'll hopefully submit a PR on that tomorrow or so btw). Of course I won't discourage a first time contributor so maybe we can join forces on this one somehow! I however think CMake [config files](https://cmake.org/cmake/help/v3.14/manual/cmake-packages.7.html#config-file-packages) are the way to go over find modules nowadays.

**Comment by VileLasagna** [comment]
@psalz I do agree that config modules are the way to go, just find writing more classic style modules easier to do by hand (but still providing actual targets). My initial plan was to look at findHIP.cmake and how they're managing the build from there to get a starting point. If you make a PR and/or link a fork, I can help you iterate on this for sure. As I've mentioned, I've got some stuff I want to work on before so I should start looking at this in more depth in say a week or two (still trying to get this working at all as part of a slightly less hello-wordly project to begin with).
My initial mindset behind the VAR vs parameter thing is twofold:
The VAR is probably going to be something you set through your bash profile setup and then forget for the most part
If we're bringing this into cmake, we want to be able to toggle this from CMake, so something a bit like:
```
set(HIPSYCL_PLATFORM $ENV{HIPSYCL_PLATFORM} CACHE STRING "The backend to use for hipSYCL")
set_property(CACHE HIPSYCL_PLATFORM STRINGS "cpu;hip;cuda;nvcc")
if(NOT HIPSYCL_PLATFORM)
  set(HIPSYCL_PLATFORM "cpu" CACHE STRING "The backend to use for hipSYCL")
endif()
```
Because then you'd pass the option into CMake as part of your parameters.

**Comment by illuhad** [comment]
I guess we have proper cmake support now ;)
