### ISSUE TITLE
rpath not set correctly for cpu target

### ISSUE THREAD

**Issue by mrzv** [illuhad/hipSYCL#212]
When I compile the same code for CUDA and CPU, I get a missing shared library for the CPU target. Easier to explain by example:
```
/opt/hipSYCL/CUDA/bin/syclcc-clang --hipsycl-platform=cuda --hipsycl-gpu-arch=sm_52 -O3 atomic-counter.cpp -o atomic-counter-cuda
/opt/hipSYCL/CUDA/bin/syclcc-clang --hipsycl-platform=cpu -O3 atomic-counter.cpp -o atomic-counter-cpu
```

```
ldd atomic-counter-cuda 
	linux-vdso.so.1 (0x00007ffc30b5c000)
	libcudart.so.9.2 => /opt/cuda-9.2/lib64/libcudart.so.9.2 (0x00007fb57ba72000)
	libhipSYCL_cuda.so => /opt/hipSYCL/CUDA/bin/../lib/libhipSYCL_cuda.so (0x00007fb57ba47000)
        [snip]
ldd atomic-counter-cpu 
	linux-vdso.so.1 (0x00007ffe484f9000)
	libhipSYCL_cpu.so => not found
        [snip]
```
Passing `-Wl,-rpath=...` to the CPU version fixes the problem, but I feel like this should happen automatically.

**Comment by illuhad** [comment]
What is your host compiler? We only set `-rpath` if the host compiler is clang (which is sort of our default compiler because we rely on it also for GPU code) because I suspect that the argument may look slightly different for various host compilers.. I don't want get into the mess of having to maintain tables with the flags for different compilers.

**Comment by mrzv** [comment]
How do I find that out?
```
clang --version
clang version 9.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by mrzv** [comment]
In CMake, I notice 
```
CUDA_LINK_LINE=-rpath $HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
ROCM_LINK_LINE=-rpath $HIPSYCL_ROCM_LIB_PATH -L$HIPSYCL_ROCM_LIB_PATH -lhip_hcc -lamd_comgr -lhsa-runtime64 ...
```
but nothing equivalent for the CPU. Could that be the problem?

**Comment by illuhad** [comment]
Just look at the output of `syclcc-clang` (without any arguments). It will then tell you in the section about `hipsycl-cpu-cxx` which CPU compiler it wants to use.

There is no argument for the CPU link line yet. The original line of thinking was that this is mostly unnecessary for CPU because linking there is almost trivial compared to GPU, but there has been some motivation (e.g. by @nazavode) that introducing an analogous argument for the CPU link line may still be desirable. Your question kind of underlines that :)

**Comment by illuhad** [comment]
By the way: As default CPU compiler, it uses the one that cmake had set as `CMAKE_CXX_COMPILER` when hipSYCL was compiled.

**Comment by mrzv** [comment]
Ah, then it's `/usr/bin/c++`, which is GCC. I'll fix it by setting `CMAKE_CXX_COMPILER` to clang.

**Comment by illuhad** [comment]
... you can also just edit your `$HIPSYCL_INSTALL_DIR/etc/hipSYCL/syclcc.json` instead of recompiling hipSYCL. This is where `syclcc` takes its default values from.

**Comment by mrzv** [comment]
Just to confirm: this fixed the problem.

**Comment by illuhad** [comment]
Do you still feel that there is some action that we need to take here, or can we close the issue?

**Comment by mrzv** [comment]
Nope. We can close.
