### ISSUE TITLE
Single task error

### ISSUE THREAD

**Issue by mrzv** [illuhad/hipSYCL#232]
If I take the code below that does nothing but submit a single task, I get some very strange behavior.

On CUDA, I get:
```
[hipSYCL Error] check_error: Received hipErrorUnknown,  throwing exception.
[hipSYCL Error] task_graph: submit() caught async error,  invoking async handler.
[hipSYCL Error] SYCL exception details: 'Unknown HIP error', HIP error code = 1030
```

On CPU, it either just hangs, or occasionally I get the following error:
```
test-cpu: : /opt/hipSYCL/CUDA/bin/../include/hipSYCL/contrib/hipCPU/hip/detail/queue.hpp:106: hipcpu::detail::async_queue::~async_queue(): Assertion `_enqueued_operations.empty()' failed.
```

Am I missing something obvious or is this a bug?

```
#include <CL/sycl.hpp>

namespace s = cl::sycl;

int main()
{
    s::queue q;

    q.submit([&](cl::sycl::handler& cgh)
    {
        cgh.single_task<class abc>([=]()
        {
        });
    });
}
```

**Comment by illuhad** [comment]
In SYCL 1.2.1, there's no implicit wait at queue destruction which means that this program is incorrect. try with a `q.wait_and_throw()` at the end.

**Comment by mrzv** [comment]
Ah, that's good to know. I have run into this CPU problem before (either hanging, or the same assertion failure) in a code, which runs fine under CUDA. But I haven't been able to boil it down into a simple example. Is it possible that there is a problem with the CPU scheduler, or should I assume there is a mistake somewhere in my code?

And just to confirm, your fix works here. Thanks.

**Comment by illuhad** [comment]
Well, there are no known issues on the CPU side that I'm aware of - of course this doesn't mean that there could not be a bug ;) It's more likely that something is UB and just doesn't show as a problem on CUDA rather than being a CPU specific issue.

**Comment by mrzv** [comment]
Ok. I'll keep digging to see if I can boil it down to something simple. Is there a rule for when I have to call `wait_and_throw()` explicitly? Is it the case that if a kernel touches some buffer, then it will have to execute before the buffer's destruction? Is that why I haven't encountered this issue so far?

I'll close this issue, since it's clearly resolved.

**Comment by illuhad** [comment]
You are absolutely right: When a buffer goes out of scope, the SYCL runtime is forced to make sure that all operations on it are complete because of a potential buffer writeback to the host.

The case here is pretty much the only case where you *have* to call synchronization explicitly. In a normal program flow, implicit synchronization due to the construction of host accessors or buffer destruction is usually sufficient.
Other use cases of `wait_and_throw` include situations where you want to control execution at a lower level, for example for benchmarking of kernels as we had discussed.

**Comment by illuhad** [comment]
... let me add that even if you use a buffer in the above example, I think it's still generally advisable to have a `wait()` at the end of the program if you don't have a synchronization point before the end of the program.
Otherwise you force the SYCL runtime to potentially do work when the destructors of the `main()` stack frame run, where you have zero options to handle errors because everything is already shutting down...

**Comment by mrzv** [comment]
Thanks for the explanation. What else acts as a synchronization point besides buffer destruction and an explicit `wait`?

**Comment by illuhad** [comment]
Creating a host accessor is a synchronous operation and therefore forces completion of the preceding DAG.

**Comment by mrzv** [comment]
Thanks. I'll have to read up on host accessors.
