### ISSUE TITLE
math.h file not found

### ISSUE THREAD

**Issue by Philius** [illuhad/hipSYCL#239]
`[ 50%] Building CXX object src/sycl/CMakeFiles/hipSYCL_cuda.dir/application.cpp.o
In file included from <built-in>:1:
In file included from /usr/lib/llvm-10/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:36:
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath:45:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated when compiling for sm_52.
make[2]: *** [src/sycl/CMakeFiles/hipSYCL_cuda.dir/build.make:63: src/sycl/CMakeFiles/hipSYCL_cuda.dir/application.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:190: src/sycl/CMakeFiles/hipSYCL_cuda.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

Compilation previously failed with libdevice sm_52 not found which I worked around by adding -nocudalib to the cuda target compile options.

I'm running Debian Bullseye.

**Comment by illuhad** [comment]
Please describe how you have installed hipSYCL.  The error indicates that either
* your system does not provide `math.h` and other standard headers. Do you have essential build tools/standard toolchains installed on your system? Can you compile regular C or C++ applications with your system compiler?
* clang cannot find the standard system headers or the include path order is wrong. Please post the output of  `clang++ -E -x c++ - -v < /dev/null`

> Compilation previously failed with libdevice sm_52 not found which I worked around by adding -nocudalib to the cuda target compile options.

Don't do this, you will not get a working program when compiling with this option. When compiling for CUDA, clang needs the CUDA device libraries.
This error indicates that clang cannot find your CUDA installation. A typical cause for this is a CUDA installation using system packages that split CUDA up into `/usr/bin`, `/usr/lib` etc which clang cannot handle. Instead, clang requires that CUDA must be installed into its own root directory, e.g. `$PREFIX/cuda`.
This is also described by the [LLVM documentation](https://www.llvm.org/docs/CompileCudaWithLLVM.html) on compiling cuda with clang.

This error might also be caused by your CUDA version being unsupported by clang. Note that clang 10 doesn't support CUDA 10.2 yet.

**Comment by Philius** [comment]
I reverted to clang/llvm 9 to see if things improved.
Debian Bullseye has nvidia cuda sdk version 10.1.
dpkg -S '*nvvm/libdevice*' results in nvidia-cuda-toolkit: /usr/lib/cuda/nvvm/libdevice
I tried setting the cuda sdk directory to /usr/lib/cuda
but that didn't get into build/syclcc.json.
After I changed default-cuda-path in build/syclcc.json to /usr/lib/cuda the build completed.

I used strace to figure out that clang 8 doesn't try to open /usr/lib/cuda/nvvm/libdevice/libdevice.10.bc
I guess it's looking for discrete files.

Anyway, hipSycl installed, I have a GTX1070, so

syclcc -O2 --hipsycl-gpu-arch=sm_61 -o test test.cpp
succeeded.

Running ./test
resulted in
Result:
0
4
0
8
0

Is this correct?

**Comment by illuhad** [comment]
> I tried setting the cuda sdk directory to /usr/lib/cuda but that didn't get into build/syclcc.json.

The right cmake argument is `CUDA_TOOLKIT_ROOT_DIR`, not the SDK one.

> I used strace to figure out that clang 8 doesn't try to open /usr/lib/cuda/nvvm/libdevice/libdevice.10.bc. I guess it's looking for discrete files.

For clang 8, I could also imagine that CUDA 10.1 is too new, so it doesn't correctly recognize the libdevice files or expects them in a differerent naming scheme etc.

> Is this correct?

Yes, seems you got a working installation :)

**Comment by Philius** [comment]
Not setting CUDA_TOOLKIT_ROOT_DIR may explain clang 10 not working.
Setting it updates syclcc.json.
Anyway milestone complete, closing.
