### ISSUE TITLE
Pinned memory usage

### ISSUE THREAD

**Issue by BanuCalin** [illuhad/hipSYCL#245]
Is there any documentation about using Cuda pinned memory ?
I managed to do it from host to device but not the other way around and I can see cudaHostAlloc in nvprof.
What I am trying to do is have a single buffer(instantiated only once) for output data, from device to host, using pinned memory, and use it along with multiple kernel calls (write mode accessor).

**Comment by illuhad** [comment]
Can you please describe what you have done so far? There is a semi-official extension in hipSYCL that introduces the new buffer property `sycl::hipsycl::property::buffer::try_pinned_memory`. This will cause the SYCL buffer to attempt to allocate its host side memory using CUDA pinned memory.

Of course, if using that property you should not construct the buffer using an external pointer since you want the buffer to allocate its own memory (which would then be pinned), e.g. something like:

```
sycl::buffer<T,1> buff{
  sycl::range<1>{size}, 
  sycl::property_list{sycl::hipsycl::property::buffer::try_pinned_memory{}}
};
```

**Comment by BanuCalin** [comment]
For my dissertation project, I am trying to optimize a gas sensor simulator. The most intensive part of that software consists of doing linear interpolations on ordered arrays. I am comparing the sycl (hipsycl) with Cuda and CPU to see if we will benefit from GPU.
You can see some code here: [https://gitlab.com/banucalin/betaboltz-conv-opt/-/blob/kernel_V_0_4/src/computegpu.cpp]( https://gitlab.com/banucalin/betaboltz-conv-opt/-/blob/kernel_V_0_4/src/computegpu.cpp)
I managed to change the buffer to use pinned memory but I have to instantiate it every time I call the kernel and it is more costly than without.
From what I have understood, data gets transferred from GPU when the object's destructor gets called.
What I need is a way to instantiate it once but use it to transfer data every iteration. I have some constant input buffers that I use in this way.

**Comment by illuhad** [comment]
> I managed to change the buffer to use pinned memory but I have to instantiate it every time I call the kernel and it is more costly than without.

Of course! Allocating pinned memory is a costly allocation which is why the buffer doesn't do it by default. Additionally, you are using `set_final_data()` which forces the buffer to copy its data to a place different than the fancy pinned memory you told it to allocate. So, the pinned memory is not even taking effect :)

`buffer` is not merely a device-side view of some some host data as you describe. It manages data allocations on multiple devices, *including the host*. This means it has its own internal host storage that you can access. This is done using host accessors:

```
q.submit([&](sycl::handler& cgh){
  auto dev_access =  buff.get_access<sycl::access::mode::write>(cgh);
  // ...
  // some kernel invocation here
});
// Access the host side data of the buffer. If the buffer has been modified on device,
// the SYCL runtime will copy it back to its internal host side storage (which is pinned memory
// when using the try_pinned_memory property). This also acts as synchronization point,
// i.e. the SYCL runtime will wait for all previous operations on this data to complete
auto host_access = buff.get_access<sycl::access::mode::read>();
// host_access can be used like regular accessors, e.g. with operator[]. If you want a raw pointer,
// you can use host_access.get_pointer()
```
So, having the buffer copy data back on destruction is only one means of moving data back to the host.  Other methods include the SYCL explicit `copy()` functions, host accessors as shown here, or the `update_host()` function.

In general, a `buffer` is a complex abstraction, and constructing one will have non-zero cost. If you find yourself creating huge amounts of buffers in performance-critical code you are doing it wrong ;)

**Comment by BanuCalin** [comment]
Ok, got it, I understand now. Implemented it and knocked some us off. Thank you very much!
