### ISSUE TITLE
Integrating with CUDA code

### ISSUE THREAD

**Issue by mrzv** [illuhad/hipSYCL#268]
I'd like to integrate SYCL code with pure CUDA code. Is there a way to do this? Specifically, is there a way for me to turn `cudaMalloc`ed memory into a `cl::sycl::buffer`?

**Comment by illuhad** [comment]
Yes, in general you can mix-and-match SYCL code with CUDA code in hipSYCL. However, constructing `sycl::buffer` from a device pointer is not yet possible because the generalized backend interop API that will be coming with SYCL 2020 is not there yet.
You can however just capture the device pointer in your SYCL kernel and use it directly.

**Comment by mrzv** [comment]
Hm, would you be open to making the member variables of `accessor` protected? Then, if I'm understanding the code correctly, one could make an accessor out of the device pointer and the existing code that needs an accessor would work correctly.

**Comment by illuhad** [comment]
I think there's a lot of merit to having a way to construct accessors based on pointers in general. This also makes a lot of sense with the upcoming unified shared memory interface in SYCL 2020, which adds explicit pointer-based data management to SYCL (similar to CUDA). I would suggest waiting a couple more days until SYCL 2020 provisional is released so that we know which API we need to integrate with ;)

**Comment by keryell** [comment]
More generally, constructing a buffer from a USM pointer is an interesting feature for writing cleaner code, efficient in the USM context while still allowing non-USM behaviour with other devices in the machine.

**Comment by illuhad** [comment]
@keryell Agreed! We need some solid interop between USM pointers (which CUDA device pointers in hipSYCL would be) and existing SYCL abstractions.

**Comment by illuhad** [comment]
Just discovered that this is still open, we now have solid USM-buffer interop: https://github.com/illuhad/hipSYCL/blob/develop/doc/buffer-usm-interop.md
