### ISSUE TITLE
Request for passing clang options through compiler wrapper

### ISSUE THREAD

**Issue by tomdeakin** [illuhad/hipSYCL#285]
On systems with older glibc (that is a very many supercomputers!), the default GCC and glibc is old. A workaround is to install your own modern GCC, build LLVM against that, and then use those two to build hipSYCL. However, this runs into some CMake configuration issues because `clang++` needs to have a `--gcc-toolchain=/path/to/modern/gcc` for the HIP and CUDA paths specifically.

Edit: Note this is at hipSYCL build time. The wrapper (once you have hipSYCL built) does this at user-code compile-time.

**Comment by illuhad** [comment]
Hi Tom, thanks for bringing that up -- I think something like this for compiler flags in analogy to `ROCM_LINK_LINE` and `CUDA_LINK_LINE` makes a lot of sense.

*If* you are root (which is usually not the case on HPC systems..) and on a Red Hat/CentOS system the easiest fix would be to install the devtoolset packages as clang looks for those.

The good news is that at build time, hipSYCL-next (branch `feature/new-runtime`) will not have this issue because there hipSYCL is built with a regular compiler and not with `syclcc` or clang CUDA/HIP. So your particular issue is already fixed on that branch :)

It still makes sense to enable this as a convenience feature for a user using `syclcc` later on. We will need to restructure `syclcc` somewhat in the future anyway to allow compiling for multiple backends/targets in the future. That might be a good time to put support for configurable compile options into `syclcc`.

**Comment by illuhad** [comment]
I think this issue no longer applies:
* `syclcc` is no longer required for building hipSYCL, and hipSYCL can be built with regular C++ compilers;
* adding custom flags to `syclcc`'s compiler invocation is addressed in #392

Please reopen if I am mistaken.
