### ISSUE TITLE
Strategy: The future of the source-to-source transformation

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#42]
Since we'll have a clang plugin hopefully soonish that will directly allow the clang CUDA/HIP frontend to ingest SYCL code (see issue #34), we could in principle drop the source-to-source transformation entirely.
I'd like to start a discussion here with hipSYCL users and developers to get some feedback on possible futures of the hipSYCL compilation toolchain. Is the source-to-source transformation important to you and we should support both source-to-source and the new clang plugin? Do you need nvcc support? Or is clang support (with the plugin) sufficient for you?

Here are some pros of the source-to-source transformation that come to my mind:
* Allows compilation of SYCL code with nvcc. This can be interesting from a marketing position ("you can do anything that nvcc can and can use the newest CUDA features right away")
* Possible to specify areas in the code with preprocessor definitions that hipSYCL shouldn't modify. This could be beneficial if you're interested in mix-and-match with SYCL and CUDA/HIP code.

The new clang plugin on the other hand gives us:
* Much more robustness and reliability (there are edge cases in the source-to-source transformation...)
* Faster compilation speed
* Solid SYCL support
* Paves the way for runtime selection whether a kernel should be executed on host or device (could in principle however also be implemented with source-to-source and clang's CUDA implementation [but likely not with nvcc])
* Potentially even some parts of the C++ standard library could be used in kernels (although not yet with the initial version of the plugin)
* Implementation of specific optimizations in the future since we have access to the IR

While not impossible, it may require some additional effort to support both the current source-to-source transformation and the new clang plugin approach because the clang plugin treats any function without attributes implicitly as `__host__ __device__`. This means that all functions for SYCL kernels (e.g. math functions) must also support compilation for both host and device. At the moment, we assume in the runtime that everything used in kernels is `__device__` only. This is also assumed by the current source-to-source transformation.
Also, if we still have to support source-to-source, it may limit our ability to implement things with IR transformations.

**Comment by VileLasagna** [comment]
Dropping the transformation step does look attractive from a compiling time standpoint and increased robustness is always good. As much as I'm tempted to just get into a "light the torches" mood, there are a couple of niggles with dropping nvcc:

 - Might become a semi-non-issue in the future as it catches up better but being tied to older versions of CUDA because clang can't handle them yet can get nasty.
 - There's always the question of whether clang can match nvcc for performance on the card... and, granted, I haven't seen any numbers in a while. Will say that increased robustness topples this if the difference is not significant (lots of subjective hand-wavy terms here, though)

All in all, I'm tempted to say that simplifying the build is always good and I'm excited by the possibility of shoving yet more work into clang

**Comment by illuhad** [comment]
Thanks for the feedback! It's indeed rather difficult to find recent comparisons of nvcc vs clang. One of the more interesting ones I've found was [this](https://arxiv.org/pdf/1711.01845.pdf) (compares clang 6 vs nvcc 9, i.e. CUDA 9, so already older). The conclusion was that clang is very competitive or even better than nvcc. If that's still the case today, I don't know, although I suspect it is.
As clang 8 already supports CUDA 10 the only CUDA version that's still unsupported to my knowledge is 10.1. Since CUDA 10.1 is still quite new, for me personally that would be acceptable.

We're already using clang as default CUDA compiler instead of nvcc because nvcc already imposes some restrictions with the current source-to-source transformation approach (e.g. limitations with regards to instantiating kernels with lambda functions, which is of course quite important for SYCL). So, nvcc is already kind of a second class citizen, and users that just use the defaults won't see any differences with regards to performance or CUDA version support if we drop the source-to-source transformation.

I agree with your points though, and obtaining native CUDA performance and support for the newest CUDA versions has always been one of the ideas behind the hipSYCL project. In the end, it's a matter of balancing the quality of SYCL support and the quality of the CUDA backend. 
Personally, I'm tending towards the stance that the first priority of a SYCL implementation should be solid SYCL support, but I'd love to hear from people if there are other use cases that require different priorities :)

**Comment by illuhad** [comment]
Idea: We could also have two modes of support:
* "full SYCL mode": Uses the clang plugin to provide the best SYCL support possible. Only this mode would be supported in a fully-automated fashion in `syclcc`.
* "manual mode": Requires the user to manually do the steps to have CUDA/HIP compilers accept the code, i.e. marking kernel lambdas (and all functions called) as `__device__`, ensuring proper semantics in hierarchical parallel for kernels and so on. This mode would target the more experienced users and provide the best HIP/CUDA interoperability and also support nvcc.

Manual mode would not be integrated in some kind of fully-automated fashion as we do with `syclcc`. However, since we already have the source-to-source transformation tools, we can let users rely on those to simplify the conversion of their source into "manual mode" SYCL if they like, similar to how e.g. `hipify-clang` can be used to translate CUDA code to HIP in an explicit step. The big difference would be that if there's an edge case in the source-to-source transformation or compiler parameter handling, it wouldn't be a showstopper bug in hipSYCL since the user has full control over how the source is compiled and the source itself.
This could be a compromise between keeping nvcc support (at least to some extent) while still relieving us of the burden to maintain the source-to-source toolchain as top priority with all its difficulties.
Is there interest in supporting "manual mode", or do you think that it's not needed?

**Comment by psalz** [comment]
Generally I'm all in favor of dropping the transformation pass entirely, as it has caused me many headaches in the past. I do like the idea of the "manual mode" however: If anyone absolutely requires `nvcc`, then they're likely not writing fully spec conformant SYCL code anyways, so it doesn't really change much (other than being a slight inconvenience) if they also add those attributes manually. If the transformation tools are kept around then that's even less of a downside (but maybe they should be moved to a separate repository?).

Out of interest (without having ever used it): How does this affect the AMD backend? Since `hcc` is being deprecated anyways, I presume hipSYCL's support for it will be dropped as well? Can Clang currently produce binaries from HIP code that simply run on AMD?

I was thinking about adding some custom Clang diagnostics for common mistakes further down the line; for example when trying to capture a host accessor into the kernel lambda (which I've run into more often than I'd like to admit...). I presume that would still also be possible from within a Clang plugin, right?

Lastly, there is the slightly more problematic issue of Clang sometimes producing seemingly faulty CUDA executables. I've alluded to this in the past; I've encountered several situations where Clang would produce an executable that would silently fail and simply not run any kernel code. The first time I saw this was when I was evaluating Catch2 vs Boost.Test. Back then I thought it was due to the complexity of the Catch2 template code, however, since then I've seen it happen a couple more times, especially while implementing various unit tests (using Boost.Test). As is often with compiler bugs, it's really hard to predict when this occurs and how it can be avoided.  At one point I even already had a workaround for some unit test in place that I planned on including in a pull request, but then the bug vanished again after I moved some code around in a test case.

Now I've actually got a piece of code that demonstrates this bug. Check out this beacon of complexity:

```c++
#include <CL/sycl.hpp>

int main() {
    cl::sycl::queue queue;
    cl::sycl::buffer<float, 1> buf(10);

    queue.submit([&](cl::sycl::handler& cgh) {}); // The culprit

    queue.submit([&](cl::sycl::handler& cgh) {
        auto acc = buf.get_access<cl::sycl::access::mode::discard_write>(cgh);
        cgh.parallel_for<class fail>(buf.get_range(), [=](cl::sycl::item<1> item) {
            acc[item] = 1.f;
        }); 
    }); 

    return 0;
}
```
When compiled with `nvcc`, this runs fine. If compiled with Clang, everything seems to be fine at first as well. The hipSYCL debug output confirms that a task has been submitted and the graph node then also completes as expected. However, this kernel never actually runs. Executing this through `cuda-memcheck` reveals that `Program hit cudaErrorInvalidDeviceFunction (error 8) due to "invalid device function" on CUDA API call to cudaLaunch.`. This is using `clang version 8.0.0-svn356034-1~exp1~20190313093039.54 (branches/release_80)`.

If I comment out that empty command group, everything works again. I spent some time a couple of weeks ago, trying to get to the bottom of this - unsuccessfully. What I know is that the produced PTX is identical for both versions (extracted using `cuobjdump`), so the issue must lie elsewhere.

I’d be very interested to hear whether any of you can reproduce this. Sorry that this is slightly off-topic, however I also didn't want to open a separate issue as it (at least I think) isn't really exclusive to hipSYCL. If you can reproduce this, we should file a bug report with the LLVM developers. Before that I’d however like to narrow the issue down to a smaller example with reduced complexity that hopefully doesn’t have to `#include <CL/SYCL.hpp>` at all.

**Comment by illuhad** [comment]
> Generally I'm all in favor of dropping the transformation pass entirely, as it has caused me many headaches in the past. I do like the idea of the "manual mode" however: If anyone absolutely requires nvcc, then they're likely not writing fully spec conformant SYCL code anyways, so it doesn't really change much (other than being a slight inconvenience) if they also add those attributes manually. If the transformation tools are kept around then that's even less of a downside (but maybe they should be moved to a separate repository?).

Thanks for the feedback! 

> Out of interest (without having ever used it): How does this affect the AMD backend? Since hcc is being deprecated anyways, I presume hipSYCL's support for it will be dropped as well? Can Clang currently produce binaries from HIP code that simply run on AMD?

To my knowledge, `hcc` is a clang fork, so I would expect the clang plugin also to work with `hcc`. In any case, it's deprecated as you mention and AMD is moving to clang. Since clang 8, there is support for HIP kernel generation in mainline clang (`clang++ -x hip`, in analogy to `-x cuda`). I haven't tested it yet though. Of course, AMD support is a pillar of the hipSYCL project and we will make sure to have it working :)

> I was thinking about adding some custom Clang diagnostics for common mistakes further down the line; for example when trying to capture a host accessor into the kernel lambda (which I've run into more often than I'd like to admit...). I presume that would still also be possible from within a Clang plugin, right?

Absolutely! We can do the same things with the plugin that we can with the source transformation on the AST level, additionally we can also do anything we like on the IR level. In terms of access to clang features, we're not giving anything up, on the contrary - we get more opportunities :)

Thanks for your test case, I will try to reproduce it this evening (I'm not at my CUDA machine at the moment). This certainly sounds like a very weird problem..

**Comment by illuhad** [comment]
@psalz, I can reproduce the issue on Arch Linux with vanilla clang 8 from the repositories and CUDA 9.2. It also works again if the empty command group is moved after the non-empty one. This leads me to believe that something in that first `submit()` call modifies some state incorrectly. There are actually  some CUDA calls happening in `submit()` even with empty command group, most notably a call to `hipSetDevice()`. 
They however do not seem to related to the issue, since uncommenting `_stream->activate_device()` in `queue::submit()` does not seem to make a difference... (Also, since we are checking all HIP/CUDA return values in hipSYCL with `detail::check_error`, there shouldn't be a silent error coming from our calls in the first place).
I also had a quick look at the host llvm IR: The code generated at the `cudaLaunch` and leading up to it is exactly the same (except for switched naming of anonymous objects which just get enumerated). I've tried creating a minimal CUDA application that mimics the SYCL test case to reproduce the error for a potential LLVM Bug Report, but so far couldn't reproduce it with pure CUDA.

**Comment by psalz** [comment]
Well, I'm "glad" that you could reproduce this, so at least we can try and work this out together (maybe we should create an issue after all, where we can collect all of the evidence..?). I just ran into this again in my own project (for the first time), and it really is just very frustrating.

If this is related to some invalid CUDA state, then it must be within one of the compiler-generated functions, not inside something like `stream::activate_device()` - because how would it otherwise work with `nvcc`? Also don't fixate too much on the semantics of this particular example, as it is simply the smallest demo I could find. This bug has surfaced in totally random situations, e.g. when only having a single (non-empty) command group, or when doing an explicit copy and then a kernel invocation.

**Comment by illuhad** [comment]
clang plugin is implemented and merged. After some interim time for evaluation where both old `syclcc` and new `syclcc-clang` is available we can start removing the old stuff :)

**Comment by psalz** [comment]
Cool! First impression: I'm getting a ton of errors, including really hairy sounding ones like `fatal error: error in backend: Cannot select <...>` ;-). I'll see if I can get to the bottom of it over the next days!

**Comment by illuhad** [comment]
Is this llvm 9? I think I've seen some similar errors on ROCm (which also requires llvm 9) related to the `vec<>` API. Try clang 8 or, if you are compiling the unit tests, disabling the `vec<>` test.

**Comment by psalz** [comment]
No, this is on LLVM/Clang 8. The tests work fine, the errors I'm running into are only occurring when trying to compile my own stuff. I've however since moved past this issue, as I think it was due to non-device code sneaking in (and I know why): The first thing I had to do was to work around an apparent infinite recursion / stack overflow in `FunctionPruningIRPass::canUserBeRemoved`. I initially chose to be conservative and return `false` in case of said infinite recursion, hence presumably including non-device code in the PTX. I've since changed that behavior to return `true` and while I no longer get the previous error, I did get some `ptas` errors about unkown symbols. That in turn can be worked around by enabling compiler optimizations (Clang seems to emit a lot of junk into the PTX during debug builds). Now I am stuck at compiling a particular translation unit for the past 15 minutes. Not sure how to best proceed from here...

**Comment by psalz** [comment]
Well, it turns out my hacky workaround for the infinite recursion (copying a set of `llvm::User*`s around with each call to `canUserBeRemoved`) was a *tad* too inefficient ;-). Now it went through - amazing!

I'll investigate the cause for that infinite recursion and file an issue/PR.

**Comment by illuhad** [comment]
Ahhh, cycles in the user graph leading to an infinite recursion... I didn't think much about that because SYCL doesn't allow recursion in kernels (which is basically where we would get such cycles). But of course we shouldn't crash in that case and ideally not be more restrictive than CUDA.
If you enable compiler optimizations clang will basically its own pass to prune unused functions which is why it works in that case..

**Comment by illuhad** [comment]
Probably it's better to build a call graph and then do mark-and-sweep starting from kernels. Then recursion shouldn't be a problem. I'll see if I have some time this evening to implement this :)

**Comment by illuhad** [comment]
@psalz, could you please check if PR #66 fixes your issue? I've changed the way functions are identified for pruning from going "backwards" recursively to the callers to going "forwards" from the entrypoints to all callees. With this strategy, it's easy to treat functions correctly that we have already visited.

**Comment by keryell** [comment]
On the other hand I am not against a SYCL implementation accepting recursion in kernel code if the target can handle it... :-)

**Comment by illuhad** [comment]
Indeed :) that issue is fixed already on the master branch, so we can again handle all recursion that CUDA and ROCm backends will accept :)

**Comment by illuhad** [comment]
Closing as everything is done :)
