### ISSUE TITLE
Performance: multiple cudaSetDevice calls before kernel launch

### ISSUE THREAD

**Issue by reguly** [illuhad/hipSYCL#87]
Profiling the execution of SYCL code on NVIDIA GPUs, I see that before each kernel launch there are about 7-10 calls to cudaSetDevice. These introduce considerable latency along with whatever is done on the CPU: for my smaller application it's up to ~150 us (and the execution of my kernel is ~130 us).
I'm not sure where this is coming from, but I can't think of a reason for calling cudaSetDevice repeatedly... It would considerably help kernel launch overheads to get rid of this.

**Comment by illuhad** [comment]
Thanks for the analysis! I would definitely expect more calls than strictly necessary since SYCL does dynamic out-of-order processing, so before each operation we need to make sure that we're still on the right device (it could be that another operation on another device was executed in the meantime). However, I'm a bit surprised by that many calls to `cudaSetDevice`. I'm not sure why there would be so many before each kernel call. I'm also a bit suprised that they come with so much latency. After all, nvidia explicitly states that it [should be considered a very low overhead call. ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g159587909ffa0791bbe4b40187a4c6bb)

If `cudaSetDevice` really is so slow, we could just track the device that we're on (i.e. the device id of the last call to `cudaSetDevice`) ourselves in the hipSYCL runtime, and only call `cudaSetDevice` if we really need to switch.

Would it be possible for you to share your profiler timeline?

**Comment by reguly** [comment]
The time spent in the driver itself is actually not that bad (roughly 1-2 us), but there are considerable gaps in-between.

Below is the link for the nvprof timeline of the application. In some cases these are overlapped with kernel execution, but in others I need the synchronisation...
https://www.dropbox.com/s/o2zfxl2fagbm8ro/airfoil_sycl.nvprof?dl=0

I expect it will be very rare to be switching between devices in user code - there is probably more benefit from assuming people don't do that, and if they actually do, then do something more expensive...

**Comment by illuhad** [comment]
Thanks for sharing your timeline. While that many calls to `cudaSetDevice` are certainly a little bizarre, I actually don't think they are related to your observed kernel launch latency. I'll have to do some investigating - it could well be that the current task graph implementation needs some revamping to fix that.

**Comment by illuhad** [comment]
More recent versions of hipSYCL (0.9.x) should behave differently.
