### ISSUE TITLE
syclcc-clang fails to build libhipsycl_rocm: missing basic cstdint types (uint8_t, etc..)

### ISSUE THREAD

**Issue by VileLasagna** [illuhad/hipSYCL#93]
So, I've updating things on my end and testing out the new syclcc-clang stuff now that the change by psalz on the CMake side. Took me a while to sort out the whole rocm side, updating everything to 2.6 (still not quite done there), understanding and migrating to the hip-clang plugin... But after some back and forth I've done it and quite like not having to rely on hcc.

Still not 100% and this issue is about one problem which I actually found a fix to. As I was getting this up, the issue mentioned in #74 where clang would fail the build complaining about not knowing basic int types was back. After banging my head in frustration for a while, I've managed to sort it out and am going to open a PR for it, would just like to confirm direction for the fix.

The root cause of the issue is that clang was trying to load incorrect internal headers. In my case, as I've built the packages from source from my fork of Experimental_ROC, rocm's raw clang gets put into `<rocm_path>/llvm/` with the executables in `bin` and the headers located in `lib/clang/9.0.0/include` 

This is relevant because in line 434, syclcc-clang looks for these files in `<rocm_path>/hcc/lib/clang`, which are still there because I have hcc as well (it's still required to build HC and is it's final release). Turns out those headers don't quite match up and the fix for the build is correcting that path.

My doubt here, though, is that I'm somewhat surprised I seem to be the first one bumping into this issue given how it happens. Not returning that path explicitly seems to cause troubles as well (I've tried to return empty or `/usr/include` and build did not succeed).

As such I'm trying to both understand a bit more how come no one else seems to have this issue as well as what would be the ideal fix to put in the PR.

My suggestion would be walking back one dir up from `hipsycl-clang`'s location and, from there, look into `/lib/clang` instead of assuming the full path. Again, only unsure because I seem to be the odd one out here =P

ps: I've mentioned that this is not the only issue I'm having, and while this is true, the others are not related to this one and aren't things that I've explored. Just for curiosity's sake, here they are:
 - My performance on CPU is very very bad. My own version of toybrot with OpenMP takes about 1-1.5 secs, and this is taking 15 and not behaving. But I think this is on the included project so not quite hipsycl's scope
 - I've also been trying to build CUDA from the same clang. On it's own it seems to work fine but my project through hipsycl just crashes out. I haven't begun investigating this yet
 - I'm going to open a pr with a change to the ADD_SYCL_TO_TARGET CMake macro to enable us to forward hipsycl-platform per target. Reasoning is I want to be able to have the same project build, say, `tbSYCL-rocm``tbSYCL-cuda` and `tbSYCL-openmp` all at once. The way we're currently doing it, we need to change the cmake cache variable and also delete the build folder as CMake doesn't even invalidate the build when you do it, so it's still a little clunky in this one very specific area

**Comment by illuhad** [comment]
Thanks for letting me know! That path is indeed a remnant of the old `syclcc` configuration using `hcc`. This is definitely incorrect and should be updated. It could be that nobody noticed because for some combinations of `hcc` and `hip-clang` perhaps it worked.. but I don't know.

Your proposed approach of starting from `hipsycl-clang` and going up is also the one I would have suggested. Looking forward to your PR :)

Regarding your other issues:
* CPU performance: I'm a bit surprised it was only 10 times slower ;) I'm aware that the CPU backend is massively inefficient (I think this is also mentioned in the readme). I'm actually working on that right now. PR #90 contains some explanations on why this is the case and should already improve performance for all kernel invocations except `ndrange` parallel for. Another patch that I'm still working on at the moment is switching to a unified memory model on CPU. Currently, it still does "data transfers" even when on CPU which is of course both inefficient and unnecessary.
* I've never tried using the CUDA backend with hip-clang. Perhaps AMD broke that in their fork?
* Passing hipsycl platform per target sounds like a good improvement!

**Comment by illuhad** [comment]
Fixed by PR #113.
